config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :educations
  resources :experiences
  resources :links
  resources :technologies
  resources :blogs
  resources :projects
  resources :users
  root 'pages#home'
  get 'blogs/sort/:id', to: 'blogs#sort'
  get 'projects/sort/:id', to: 'projects#sort'
  get 'sessions/new', to: 'sessions#new', as: 'new_login'
  post 'sessions', to: 'sessions#create', as: 'login'
  delete 'sessions', to: 'sessions#destroy', as: "destroy_session"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    has_many :blog_technologies
    has_many :technologies, through: :blog_technologies
end

app/models/blog_technology.rb
class BlogTechnology < ApplicationRecord
  belongs_to :blog
  belongs_to :technology
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user
  has_many :education_technologies
  has_many :technologies, through: :education_technologies
  has_many :education_skills
  has_many :skills, through: :education_skills
end

app/models/education_skill.rb
class EducationSkill < ApplicationRecord
  belongs_to :education
  belongs_to :skill
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_many :experience_technologies
  has_many :technologies, through: :experience_technologies

  has_many :experience_skills
  has_many :skills, through: :experience_skills
end

app/models/experience_skill.rb
class ExperienceSkill < ApplicationRecord
  belongs_to :experience
  belongs_to :skill
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :project_technologies
  has_many :technologies, through: :project_technologies
end

app/models/project_technology.rb
class ProjectTechnology < ApplicationRecord
  belongs_to :project
  belongs_to :technology
end

app/models/skill.rb
class Skill < ApplicationRecord
    belongs_to :user
    has_many :education_skills
    has_many :educations, through: :education_skills
    has_many :experiences_skills
    has_many :experiences, through: :experiences_skills
end

app/models/technology.rb
class Technology < ApplicationRecord
    belongs_to :user
    has_many :project_technologies
    has_many :projects, through: :project_technologies
    has_many :blog_technologies
    has_many :blogs, through: :blog_technologies
    has_many :education_technologies
    has_many :educations, through: :education_technologies
    has_many :experience_technologies
    has_many :experiences, through: :experience_technologies 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :technologies
    has_many :projects 
    has_many :blogs
    has_many :links
    has_many :educations 
    has_many :experiences
    has_many :skills
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :logged_in, only: [:new, :create, :show]


  # GET /users/1 or /users/1.json
  def show
    @technologies = @user.technologies.order(name: :asc)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
        session[:user_id] = @user.id 
        redirect_to user_path(@user)
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        flash[:errors] = @user.errors.full_messages 
        redirect_to new_user_path
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :first_name, :last_name, :title, :image, :tech_bio, :bio, :location)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :tech_bio %>
    <%= form.text_area :tech_bio %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <div class="new-form">
                <h1>Edit User</h1>
                <%= render 'form', user: @user %>
                <%= link_to 'Back', user_path(@current_user.id) %>
            </div>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <div class="new-form">
                <h1>New User</h1>
                <%= render 'form', user: @user %>
                <%= link_to 'Back', user_path(@current_user.id) %>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row" id="my-info">
    <div class="heading">
      <h2><%= @user.first_name + " " + @user.last_name %></h2>
      <%= button_to "Edit", edit_user_path(@user), method: :get, class: "btn btn-outline-primary" %>
    </div>
    <hr>
    <div class="col-2">
        <%= image_tag(@user.image, class: "img-thumbnail", id: "user-image", alt: "user image")%>
    </div>

    <div class="col-4">
      <h4>Title: <%= @user.title %></h4>
      <h4>Email: <%= @user.email %></h4>
      <h4>Location: <%= @user.location %></h4>
    </div>

    <div class="col-6">
      <p><strong>Bio: </strong><%= @user.bio %></p>
      <p><strong>Tech Bio: </strong><%= @user.tech_bio %></p>
    </div>
  </div>

  <div class="row" id="tech-row">
      <div class="col" id="links">
        <div class="heading">
          <h2>Links</h2>
          <%= button_to "Add", new_link_path, method: :get, class: "btn btn-outline-primary" %>
        </div>
        <table class="table align-middle table-hover table-sm">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Image</th>
              <th scope="col">Edit/Remove</th>
            </tr>
          </thead>
          <tbody>
            <% @user.links.each do |link| %>
              <tr>
                <td><%= link_to  link.name, link.address, target: :_blank %></td>
                <td><%= image_tag(link.image, class: "link-image", alt: "link image")%></td>
                <td><%= link_to 'Edit', edit_link_path(link) %> | <%= link_to 'Remove', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="col" id="technologies">
        <div class="heading">
          <h2>Technologies</h2>
          <%= button_to "Add", new_technology_path, method: :get, class: "btn btn-outline-primary" %>
        </div>
        <table class="table align-middle table-hover table-sm">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Image</th>
              <th scope="col">Edit/Remove</th>
            </tr>
          </thead>
          <tbody>
            <% @technologies.each do |technology| %>
              <tr>
                <td><%= link_to  technology.name, technology_path%></td>
                <td><%= image_tag(technology.image, class: "link-image", alt: "link image")%></td>
                <td><%= link_to 'Edit', edit_technology_path(technology) %> | <%= link_to 'Remove', technology, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <div class="col" id="technologies">
        <div class="heading">
          <h2>Skills</h2>
          <%= button_to "Add", new_skill_path, method: :get, class: "btn btn-outline-primary" %>
        </div>
        <table class="table align-middle table-hover table-sm">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Image</th>
              <th scope="col">Edit/Remove</th>
            </tr>
          </thead>
          <tbody>
            <% @user.skills.each do |skill| %>
              <tr>
                <td><%= link_to  skill.name, skill_path%></td>
                <td><%= image_tag(skill.image, class: "link-image", alt: "link image")%></td>
                <td><%= link_to 'Edit', edit_skill_path(skill) %> | <%= link_to 'Remove', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>


  <div class="row" id="info">
    <div class="col" id="projects">
    <div class="heading">
      <h2><%= link_to  "Projects", projects_path %></h2>
      <%= button_to "Add", new_project_path, method: :get, class: "btn btn-outline-primary" %>
    
    </div>
      <ul class="list-group">
        <% @user.projects.each do |project|%>
          <li class="list-group-item list-group-item-dark"><%= link_to  project.name, project_path(project) %></li>
        <% end %>
      </ul>
    </div>

    <div class="col">
    <div class="heading">
      <h2><%= link_to  "Blogs", blogs_path %></h2>
      <%= button_to "Add", new_blog_path, method: :get, class: "btn btn-outline-primary" %>
    </div>
      <ul class="list-group">
        <% @user.blogs.each do |blog| %>
          <li class="list-group-item list-group-item-dark"><%= link_to  blog.title, blog_path(blog) %></li>
        <% end %>
      </ul>
    </div>

    <div class="col">
      <div class="heading">
        <h2> <%= link_to  "Experiences", experiences_path %></h2>
        <%= button_to "Add", new_experience_path, method: :get, class: "btn btn-outline-primary" %>
      </div>
      <ul class="list-group">
        <% @user.experiences.each do |experience| %>
          <li class="list-group-item list-group-item-dark"><%= link_to  experience.title, experience_path(experience) %></li>
        <% end %>
      </ul>
    </div>

    <div class='col'>
      <div class="heading">
        <h2> <%= link_to  "Educations", educations_path %></h2>
        <%= button_to "Add", new_education_path, method: :get, class: "btn btn-outline-primary" %>
      </div>
      <ul class="list-group">
        <% @user.educations.each do |education| %>
          <li class="list-group-item list-group-item-dark"><%= link_to  education.title, education_path(education) %></li>
        <% end %>
      </ul>
    </div>
  </div>
    </div>
  <br>
  <br>
</div>