config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :educations
  resources :experiences
  resources :links
  resources :technologies
  resources :blogs
  resources :projects
  resources :users
  root 'pages#home'
  get 'blogs/sort/:id', to: 'blogs#sort'
  get 'projects/sort/:id', to: 'projects#sort'
  get 'sessions/new', to: 'sessions#new', as: 'new_login'
  post 'sessions', to: 'sessions#create', as: 'login'
  delete 'sessions', to: 'sessions#destroy', as: "destroy_session"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    has_many :blog_technologies
    has_many :technologies, through: :blog_technologies
end

app/models/blog_technology.rb
class BlogTechnology < ApplicationRecord
  belongs_to :blog
  belongs_to :technology
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user
  has_many :education_technologies
  has_many :technologies, through: :education_technologies
  has_many :education_skills
  has_many :skills, through: :education_skills
end

app/models/education_skill.rb
class EducationSkill < ApplicationRecord
  belongs_to :education
  belongs_to :skill
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_many :experience_technologies
  has_many :technologies, through: :experience_technologies

  has_many :experience_skills
  has_many :skills, through: :experience_skills
end

app/models/experience_skill.rb
class ExperienceSkill < ApplicationRecord
  belongs_to :experience
  belongs_to :skill
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :project_technologies
  has_many :technologies, through: :project_technologies
end

app/models/project_technology.rb
class ProjectTechnology < ApplicationRecord
  belongs_to :project
  belongs_to :technology
end

app/models/skill.rb
class Skill < ApplicationRecord
    belongs_to :user
    has_many :education_skills
    has_many :educations, through: :education_skills
    has_many :experiences_skills
    has_many :experiences, through: :experiences_skills
end

app/models/technology.rb
class Technology < ApplicationRecord
    belongs_to :user
    has_many :project_technologies
    has_many :projects, through: :project_technologies
    has_many :blog_technologies
    has_many :blogs, through: :blog_technologies
    has_many :education_technologies
    has_many :educations, through: :education_technologies
    has_many :experience_technologies
    has_many :experiences, through: :experience_technologies 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :technologies
    has_many :projects 
    has_many :blogs
    has_many :links
    has_many :educations 
    has_many :experiences
    has_many :skills
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  skip_before_action :logged_in, only: [:show, :sort]
  # GET /projects or /projects.json
  def index
    @projects = @current_user.projects
  end

  def sort
    technology = Technology.find(params[:id])
    render json: technology.projects, :include => :technologies
  end 

  # GET /projects/1 or /projects/1.json
  def show

  end

  # GET /projects/new
  def new
    @project = Project.new

  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = @current_user.id
    params[:technologies][:id].each do |technology_id|
      if !technology_id.empty?
        @project.project_technologies.build(:technology_id => technology_id)
      end
    end
    # byebug


    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update

    if params[:technologies][:id].length != 1 
      # destroy the old record
      @project.project_technologies.each do |tech|
        tech.destroy
      end
      #build the new ones
      params[:technologies][:id].each do |technology_id|
        if !technology_id.empty?
          @project.project_technologies.build(:technology_id => technology_id)
        end
      end
    end
    
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.technologies.destroy_all
    @project.destroy
    respond_to do |format|
      format.html { redirect_to @current_user, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :image, :address, :github, :summary, :user_id, :deployed, technologies_attributes: [:name])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group mb-3">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :github %>
    <%= form.text_field :github %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :summary %>
    <%= form.text_area :summary %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :deployed %>
    <%= form.check_box :deployed %>
  </div>

<%= fields_for(@project_technologies) do |project_technology| %>
    <div class="form-group mb-3">
      <%= project_technology.label "Technologies" %>
      <%= collection_select(:technologies, :id, Technology.all, :id, :name, {}, {:multiple =>  true}) %>
    </div>
<% end %>


  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/projects/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <div class="new-form">
                <h1>Edit Project</h1>
                <%= render 'form', project: @project %>
                <%= link_to 'Back', user_path(@current_user.id) %>
            </div>
        </div>
    </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="row">
    <div class="heading">
      <h1>Projects</h1>
      <%= button_to "Add", new_project_path, method: :get, class: "btn btn-outline-primary" %>
    </div>
    <div class="col">

      <table class="table align-middle table-hover">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Image</th>
            <th scope="col">Deployed?</th>
            <th scope="col">Github</th>
            <th scope="col">Summary</th>
            
          </tr>
        </thead>

        <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td><%= link_to  project.name, project_path(project.id) %></td>
              <td><%= image_tag(project.image, class: "project-image", alt: "project image")%></td>
              <% if project.deployed %>
                <td><%= link_to  project.deployed, project.address, target: :_blank %></td>
              <% else %>
                <td><%= project.deployed %></td>
              <% end %>
              <td><%= link_to  "Github", project.github, target: :_blank %></td>
              <td><%= project.summary %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <div class="new-form">
                <h1>New Project</h1>
                <%= render 'form', project: @project %>
                <%= link_to 'Back', user_path(@current_user.id) %>
            </div>
        </div>
    </div>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="show-container">
    <div class="row">
        <div class="heading">
          <h1><%= @project.name %></h1>
          <%= button_to "Edit", edit_project_path, method: :get, class: "btn btn-outline-primary" %>
          <%= button_to "Delete", @project, :method => "delete", class: "btn btn-outline-danger", data: { confirm: 'Are you sure?' } %>
        </div>
        <div class="col">
          <%= image_tag(@project.image, class: "img-thumbnail", alt: "project image")%>
        </div>
        <div class="col">
          <% if @project.deployed %>
            <h4><%= link_to  "Deployed", @project.address, target: :_blank %></h4>
          <% end %>
            <h4><%= link_to  "GitHub", @project.github, target: :_blank %></h4>
            <h4>Technologies: </h4>
            <ul>
              <% @project.technologies.each do |technology| %>
                <li><%= technology.name %></li>
              <% end %>
            </ul>
        </div>
        <p></p>
        <h2>Summary: </h2>
        <p><%= @project.summary %></p>
    </div>
  </div>
</div>