config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :educations
  resources :experiences
  resources :links
  resources :technologies
  resources :blogs
  resources :projects
  resources :users
  root 'pages#home'
  get 'blogs/sort/:id', to: 'blogs#sort'
  get 'projects/sort/:id', to: 'projects#sort'
  get 'sessions/new', to: 'sessions#new', as: 'new_login'
  post 'sessions', to: 'sessions#create', as: 'login'
  delete 'sessions', to: 'sessions#destroy', as: "destroy_session"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    has_many :blog_technologies
    has_many :technologies, through: :blog_technologies
end

app/models/blog_technology.rb
class BlogTechnology < ApplicationRecord
  belongs_to :blog
  belongs_to :technology
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user
  has_many :education_technologies
  has_many :technologies, through: :education_technologies
  has_many :education_skills
  has_many :skills, through: :education_skills
end

app/models/education_skill.rb
class EducationSkill < ApplicationRecord
  belongs_to :education
  belongs_to :skill
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_many :experience_technologies
  has_many :technologies, through: :experience_technologies

  has_many :experience_skills
  has_many :skills, through: :experience_skills
end

app/models/experience_skill.rb
class ExperienceSkill < ApplicationRecord
  belongs_to :experience
  belongs_to :skill
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :project_technologies
  has_many :technologies, through: :project_technologies
end

app/models/project_technology.rb
class ProjectTechnology < ApplicationRecord
  belongs_to :project
  belongs_to :technology
end

app/models/skill.rb
class Skill < ApplicationRecord
    belongs_to :user
    has_many :education_skills
    has_many :educations, through: :education_skills
    has_many :experiences_skills
    has_many :experiences, through: :experiences_skills
end

app/models/technology.rb
class Technology < ApplicationRecord
    belongs_to :user
    has_many :project_technologies
    has_many :projects, through: :project_technologies
    has_many :blog_technologies
    has_many :blogs, through: :blog_technologies
    has_many :education_technologies
    has_many :educations, through: :education_technologies
    has_many :experience_technologies
    has_many :experiences, through: :experience_technologies 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :technologies
    has_many :projects 
    has_many :blogs
    has_many :links
    has_many :educations 
    has_many :experiences
    has_many :skills
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: %i[ show edit update destroy ]

  # GET /experiences or /experiences.json
  def index
    @experiences = @current_user.experiences
  end

  # GET /experiences/1 or /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences or /experiences.json
  def create
    @experience = Experience.new(experience_params)
    @experience.user_id = @current_user.id

    params[:technologies][:id].each do |technology_id|
      if !technology_id.empty?
        @experience.experience_technologies.build(:technology_id => technology_id)
      end
    end

    params[:skills][:id].each do |skill_id|
      if !skill_id.empty?
        @experience.experience_skills.build(:skill_id => skill_id)
      end
    end

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: "Experience was successfully created." }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1 or /experiences/1.json
  def update

    if params[:technologies][:id].length != 1 
      # destroy the old record
      @experience.experience_technologies.each do |tech|
        tech.destroy
      end
      #build the new ones
      params[:technologies][:id].each do |technology_id|
        if !technology_id.empty?
          @experience.experience_technologies.build(:technology_id => technology_id)
        end
      end
    end

    if params[:skills][:id].length != 1 
      # destroy the old record
      @experience.experience_skills.each do |skill|
        skill.destroy
      end
      #build the new ones
      params[:skills][:id].each do |skill_id|
        if !skill_id.empty?
          @experience.experience_skills.build(:skill_id => skill_id)
        end
      end
    end

    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to @experience, notice: "Experience was successfully updated." }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1 or /experiences/1.json
  def destroy
    @experience.technologies.destroy_all
    @experience.skills.destroy_all
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to @current_user, notice: "Experience was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def experience_params
      params.require(:experience).permit(:start_date, :end_date, :title, :description, :user_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/experiences/_form.html.erb
<%= form_with(model: experience, local: true) do |form| %>
  <% if experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
        <% experience.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :start_date %>
    <%= form.text_field :start_date %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :end_date %>
    <%= form.text_field :end_date %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <%= fields_for(@experience_technologies) do |experience_technology| %>
    <div class="form-group mb-3">
      <%= experience_technology.label "Technologies" %>
      <%= collection_select(:technologies, :id, Technology.all, :id, :name, {}, {:multiple =>  true}) %>
    </div>
<% end %>

  <%= fields_for(@experience_skills) do |experience_skill| %>
    <div class="form-group mb-3">
      <%= experience_skill.label "Skills" %>
      <%= collection_select(:skills, :id, Skill.all, :id, :name, {}, {:multiple =>  true}) %>
    </div>
<% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <div class="new-form">
                <h1>Edit Experience</h1>
                <%= render 'form', experience: @experience %>
                <%= link_to 'Back', user_path(@current_user.id) %>
            </div>
        </div>
    </div>
</div>

app/views/experiences/index.html.erb
<div class="container">
  <div class="row">
    <div class="heading">
      <h1>Experiences</h1>
      <%= button_to "Add", new_experience_path, method: :get, class: "btn btn-outline-primary" %>
    </div>
    <div class="col">

      <table class="table align-middle table-hover">
        <thead>
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Start Date</th>
            <th scope="col">End Date</th>
            <th scope="col">Description</th>
            <th scope="col">Technologies</th>
          </tr>
        </thead>

        <tbody>
          <% @experiences.each do |experience| %>
            <tr>
              <td><%= link_to  experience.title, experience_path(experience.id) %></td>
              <td><%= experience.start_date %></td>
              <td><%= experience.end_date %></td>
              <td><%= experience.description %></td>
              <td><ol>
                    <% experience.technologies.each do |technology| %>
                      <li><%= technology.name %></li>
                  <% end %>
                </ol>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    
    </div>
  </div>
</div>

app/views/experiences/new.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <div class="new-form">
                <h1>New Experience</h1>
                <%= render 'form', experience: @experience %>
                <%= link_to 'Back', user_path(@current_user.id) %>
            </div>
        </div>
    </div>
</div>

app/views/experiences/show.html.erb
<div class="container">
    <div class="show-container">
      <div class="row">
        <div class="heading">
          <h2><%= @experience.title %></h2>
          <%= button_to "Edit", edit_experience_path, method: :get, class: "btn btn-outline-primary" %>
          <%= button_to "Delete", @experience, :method => "delete", class: "btn btn-outline-danger", data: { confirm: 'Are you sure?' } %>
        </div>
        <div class="col">
          <p>Started: <%= @experience.start_date %></p>
          <p>Ended: <%= @experience.end_date %></p>
          <p>Technologies:</p>
          <% @experience.technologies.each do |technology| %>
            <p><%= technology.name %></p>
          <% end %>
        </div>
        <div class="col">
          <h4>Description:</h4>
          <p><%= @experience.description %></p>
        </div>
    </div>
  </div>
</div>