config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :educations
  resources :experiences
  resources :links
  resources :technologies
  resources :blogs
  resources :projects
  resources :users
  root 'pages#home'
  get 'blogs/sort/:id', to: 'blogs#sort'
  get 'projects/sort/:id', to: 'projects#sort'
  get 'sessions/new', to: 'sessions#new', as: 'new_login'
  post 'sessions', to: 'sessions#create', as: 'login'
  delete 'sessions', to: 'sessions#destroy', as: "destroy_session"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    has_many :blog_technologies
    has_many :technologies, through: :blog_technologies
end

app/models/blog_technology.rb
class BlogTechnology < ApplicationRecord
  belongs_to :blog
  belongs_to :technology
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :user
  has_many :education_technologies
  has_many :technologies, through: :education_technologies
  has_many :education_skills
  has_many :skills, through: :education_skills
end

app/models/education_skill.rb
class EducationSkill < ApplicationRecord
  belongs_to :education
  belongs_to :skill
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_many :experience_technologies
  has_many :technologies, through: :experience_technologies

  has_many :experience_skills
  has_many :skills, through: :experience_skills
end

app/models/experience_skill.rb
class ExperienceSkill < ApplicationRecord
  belongs_to :experience
  belongs_to :skill
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :project_technologies
  has_many :technologies, through: :project_technologies
end

app/models/project_technology.rb
class ProjectTechnology < ApplicationRecord
  belongs_to :project
  belongs_to :technology
end

app/models/skill.rb
class Skill < ApplicationRecord
    belongs_to :user
    has_many :education_skills
    has_many :educations, through: :education_skills
    has_many :experiences_skills
    has_many :experiences, through: :experiences_skills
end

app/models/technology.rb
class Technology < ApplicationRecord
    belongs_to :user
    has_many :project_technologies
    has_many :projects, through: :project_technologies
    has_many :blog_technologies
    has_many :blogs, through: :blog_technologies
    has_many :education_technologies
    has_many :educations, through: :education_technologies
    has_many :experience_technologies
    has_many :experiences, through: :experience_technologies 
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :technologies
    has_many :projects 
    has_many :blogs
    has_many :links
    has_many :educations 
    has_many :experiences
    has_many :skills
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: %i[ show edit update destroy ]

  # GET /educations or /educations.json
  def index
    @educations = @current_user.educations
  end

  # GET /educations/1 or /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations or /educations.json
  def create
    @education = Education.new(education_params)
    @education.user_id = @current_user.id
    
    params[:skills][:id].each do |skill_id|
      if !skill_id.empty?
        @education.education_skills.build(:skill_id => skill_id)
      end 
    end 

    params[:technologies][:id].each do |technology_id|
      if !technology_id.empty?
        @education.education_technologies.build(:technology_id => technology_id)
      end
    end


    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: "Education was successfully created." }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1 or /educations/1.json
  def update

    if params[:technologies][:id].length != 1 
      # destroy the old record
      @education.education_technologies.each do |tech|
        tech.destroy
      end
      #build the new ones
      params[:technologies][:id].each do |technology_id|
        if !technology_id.empty?
          @education.education_technologies.build(:technology_id => technology_id)
        end
      end
    end

    if params[:skills][:id].length != 1 
      # destroy the old record
      @education.education_skills.each do |skill|
        skill.destroy
      end
      #build the new ones

      params[:skills][:id].each do |skill_id|
        if !skill_id.empty?
          @education.education_skills.build(:skill_id => skill_id)
        end
      end
    end

    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to @education, notice: "Education was successfully updated." }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1 or /educations/1.json
  def destroy
    @education.technologies.destroy_all
    @education.skills.destroy_all
    @education.destroy
    respond_to do |format|
      format.html { redirect_to @current_user, notice: "Education was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def education_params
      params.require(:education).permit(:end_date, :title, :description, :user_id, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/educations/_form.html.erb
<%= form_with(model: education, local: true) do |form| %>
  <% if education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
        <% education.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group mb-3">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :end_date %>
    <%= form.text_field :end_date %>
  </div>


  <div class="form-group mb-3">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <%= fields_for(@education_technologies) do |education_technology| %>
    <div class="form-group mb-3">
      <%= education_technology.label "Technologies" %>
      <%= collection_select(:technologies, :id, Technology.all, :id, :name, {}, {:multiple =>  true}) %>
    </div>
  <% end %>

    <%= fields_for(@skill_technologies) do |skill_technology| %>
    <div class="form-group mb-3">
      <%= skill_technology.label "Skills" %>
      <%= collection_select(:skills, :id, Skill.all, :id, :name, {}, {:multiple =>  true}) %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/educations/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <div class="new-form">
                <h1>Edit Education</h1>
                <%= render 'form', education: @education %>
                <%= link_to 'Back', user_path(@current_user.id) %>
            </div>
        </div>
    </div>
</div>

app/views/educations/index.html.erb
<div class="container">
  <div class="row">
    <div class="heading">
      <h1>Educations</h1>
      <%= button_to "Add", new_education_path, method: :get, class: "btn btn-outline-primary" %>
    </div>
    <div class="col">

      <table class="table align-middle table-hover">
        <thead>
          <tr>
            <th scope="col">Title</th>
            <th scope="col">End Date</th>
            <th scope="col">Description</th>
            <th scope="col">Technologies</th>
            <th scope="col">Skills</th>
            <th scope="col">Address</th>
          </tr>
        </thead>

        <tbody>
          <% @educations.each do |education| %>
            <tr>
              <td><%= link_to  education.title, education_path(education.id) %></td>
              <td><%= education.end_date %></td>
              <td><%= education.description %></td>
              <td><ol>
                    <% education.technologies.each do |technology| %>
                      <li><%= technology.name %></li>
                  <% end %>
                </ol>
              </td>
              <td><ol>
                    <% education.skills.each do |skill| %>
                      <li><%= skill.name %></li>
                  <% end %>
                </ol>
              </td>
              <td><%= link_to  "Address", education.address %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    
    </div>
  </div>
</div>

app/views/educations/new.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <div class="new-form">
                <h1>New Education</h1>
                <%= render 'form', education: @education%>
                <%= link_to 'Back', user_path(@current_user.id) %>
            </div>
        </div>
    </div>
</div>

app/views/educations/show.html.erb
<div class="container">
    <div class="show-container">
      <div class="row">
        <div class="heading">
          <h2><%= @education.title %></h2>
          <%= button_to "Edit", edit_education_path, method: :get, class: "btn btn-outline-primary" %>
          <%= button_to "Delete", @education, :method => "delete", class: "btn btn-outline-danger", data: { confirm: 'Are you sure?' } %>
        </div>
        <div class="col">
          <p>Graduated: <%= @education.end_date %></p>
          <p>Technologies:</p>
          <% @education.technologies.each do |technology| %>
            <p><%= technology.name %></p>
          <% end %>
        </div>
        <div class="col">
          <h4>Description:</h4>
          <p><%= @education.description %></p>
        </div>
    </div>
  </div>
</div>